# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BookTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for BookTracker
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  target 'BookTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
